# manage.ps1 — CircuitForge cross-platform product manager shim (Windows)
#
# Auto-detects the Python environment and delegates to
# `python -m circuitforge_core.manage`.
#
# Generated by: python -m circuitforge_core.manage install-shims
# Do not edit the logic here; edit manage.toml for product configuration.

# ── Python detection ──────────────────────────────────────────────────────────
$Python = $null

if (Test-Path ".venv\Scripts\python.exe") {
    $Python = ".venv\Scripts\python.exe"
} elseif (Test-Path "venv\Scripts\python.exe") {
    $Python = "venv\Scripts\python.exe"
} elseif ($env:CONDA_DEFAULT_ENV -and (Get-Command conda -ErrorAction SilentlyContinue)) {
    # Conda: run via `conda run` so the env is activated correctly
    & conda run -n $env:CONDA_DEFAULT_ENV python -m circuitforge_core.manage @args
    exit $LASTEXITCODE
} elseif (Get-Command python -ErrorAction SilentlyContinue) {
    $Python = "python"
} elseif (Get-Command python3 -ErrorAction SilentlyContinue) {
    $Python = "python3"
} else {
    Write-Error "No Python interpreter found. Install Python 3.11+, activate a venv, or activate a conda environment."
    exit 1
}

& $Python -m circuitforge_core.manage @args
exit $LASTEXITCODE
